=== thionealexio/FP_ESPECIALIDAD_1920/Lenguaje/XML/Animales.dtd
<!ELEMENT animales (animal+)>
<!ELEMENT animal (nombre, dieta, habitat)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dieta (#PCDATA)>
<!ELEMENT habitat (#PCDATA)>
<!ATTLIST animal codigo ID #REQUIRED>

=== thionealexio/FP_ESPECIALIDAD_1920/Lenguaje/XML/Animal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales SYSTEM "Animales.dtd">
<animales>
<animal codigo="a1">
<nombre>vulpes:vulpes-Zorro</nombre>
<dieta>Carnívoro</dieta>
<habitat>Bosque</habitat>
</animal>

<animal codigo="a2">
<nombre>Panthera Peli-Leon</nombre>
<dieta>Carnívoro</dieta>
<habitat>Sabana</habitat>
</animal>

<animal codigo="a3">
<nombre>-Tigre</nombre>
<dieta>Carnívoro</dieta>
<habitat>Bosque</habitat>
</animal>
</animales>
